更新UI显示效果;RoomInfo中增加net_error
zyzsdy/biliroku pull request #53
Opened 2020-01-03 11:18 UTC by Toxiad

更新UI显示效果;
RoomInfo中增加net_error;

2020-01-11 01:55 UTC, zyzsdy requested changes
Currently, Biliroku does **NOT** accept pull requests for UI. Could you please consider withdrawing the changes of UI part.

2020-01-11 01:55 UTC, zyzsdy commented on BiLiRoku/About.xaml
> -            <ColumnDefinition Width="335*"/>
I don't know what are you dissatisfied with ratio 129: 335, but this is implemented by design.

2020-01-11 01:55 UTC, zyzsdy commented on BiLiRoku/About.xaml.cs
> +        }
If I really need a feedback button, I guess I would jump directly to the Github Issue.

2020-01-25 06:57 UTC, Toxiad commented
> Currently, Biliroku does **NOT** accept pull requests for UI. Could you please consider withdrawing the changes of UI part.

那可以选择 #52

2020-01-25 06:57 UTC, closed without merging